services:
  backend:
    build: ./springboot-backend
    container_name: springboot-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./angular-frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
